### ISSUE TITLE
Upload SLDs to Github repo

### ISSUE THREAD

**Issue by ThiashaV** [kartoza/Woolpert#10]
Upload all SLDs and SVGs to Github so that the process can be automated.

**Comment by NyakudyaA** [comment]
@ThiashaV if the SLD's are named appropriately and correspond to a specific layer, we should automate this process when publishing the datasets from the DB. Upload them into the repo here once https://github.com/kartoza/Woolpert/pull/12 has been merged

**Comment by NyakudyaA** [comment]
This is done
