### ISSUE TITLE
Improve SLD styling and rendering

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/Woolpert#24]
# problem

Some of the styles show points clustered at the same location. We can improve the rendering of these
![image](https://github.com/kartoza/Woolpert/assets/2510900/422f0850-aff4-4a78-8f29-9731c5777d4c)

# Solution
Either do the following

- [ ] SLD rendering transformation- clustering https://www.cadlinecommunity.co.uk/hc/en-us/articles/360007541578-GeoServer-Creating-Stacked-Points
- [ ] Use some of the GeoServer SLD extensions to improve the rendering of the points

**Comment by NyakudyaA** [comment]
@ThiashaV I have adjusted the capacitor layer. The rest should look like that. Also adjust the scales to something reasonable and the text and colours to something reasonable

**Comment by ThiashaV** [comment]
Thank you @NyakudyaA. The colours we've used match the new/updated styling for each of the layers and we have adjusted the scaling and text as well. 
![image](https://github.com/kartoza/Woolpert/assets/98025261/af781f1d-a6a7-4c93-95b5-750513bc803e)

![image](https://github.com/kartoza/Woolpert/assets/98025261/5aa63f9b-0f9e-4382-af32-a529b6f6d023)

**Comment by NyakudyaA** [comment]
Thanks, @ThiashaV Can you update the thumbnails in GeoNode to reflect the new styles

**Comment by ThiashaV** [comment]
@NyakudyaA is there a way to update the thumbnails without the 'Edit' option being available in Geonode?

**Comment by ThiashaV** [comment]
updated:
![image](https://github.com/kartoza/Woolpert/assets/98025261/f168acbb-bac9-4ed0-a9f4-d6e4f7eaa5eb)

**Comment by NyakudyaA** [comment]
This is done
