### ISSUE TITLE
Improve GFI feature for layers

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/Woolpert#25]
# Problem

When you click a point for a layer you see the following

![image](https://github.com/kartoza/Woolpert/assets/2510900/25b3f42b-6f72-41b5-a059-40b62e529018)

# Solution
When the final layers have been configured we will need to configure to have friendly layer names to be visible for the layers, this will also allow us to hide the other fields. As a start please adjust the current layers making names Title Case, if a field represents a field please change it accordingly.

**Note:** - This should be kept open until final layers have been published

**Comment by Jeremy-Prior** [comment]
Current layer names updated to Title Case

**Comment by NyakudyaA** [comment]
@Jeremy-Prior We need all the layers to be handled. Also, can you hide the following fields and any other you deem might not be useful?

![Screenshot from 2023-06-30 14-57-46](https://github.com/kartoza/Woolpert/assets/2510900/ffcd8dfc-6fd8-4447-b9d0-b87c52323825)

**Comment by Jeremy-Prior** [comment]
Field names updated where possible (some fields need input from the client as to what the shorthand names actually mean)

**Comment by NyakudyaA** [comment]
This is complete, We do not have the metadata for all column names hence we cannot complete this properly so closing as this is the best we can do
