### ISSUE TITLE
Map Print Funtion

### ISSUE THREAD

**Issue by BooyeWLP** [kartoza/Woolpert#48]
We are able currently to open the print map function, however there are a few things we would like to change on it:

## Print Properties Screen
Once the print button is clicked a screen opens where the user is asked to change the properties, however there is a constraint on the vertical location that the user can drag the properties dialog. The image below shows the highest that I can pull the dialog on the screen:
![image](https://github.com/kartoza/Woolpert/assets/139763251/41ddbefe-8d51-4fbe-bd82-1442a07885af)

Due to this some properties at the bottom of the dialog cannot be changed. When I go full screen mode, it is possible to change those values, however it would be great if that vertical constraint can either be removed or moved more to the top of the screen.

## Map Legend
When adding a legend to the print layout an error is received:
![image](https://github.com/kartoza/Woolpert/assets/139763251/8442f3af-5443-4d8d-b880-baae0b60fd0b)

## Print Layout Design
Is it possible to change the GeoNode logo and name to the WAPP logo and name at the top of the layout design:
![image](https://github.com/kartoza/Woolpert/assets/139763251/3984e9fa-854b-485d-ba5d-82c4a29b5d2f)

## Downloading Map

When trying to download the map, it redirects you to a geoserver URL that says the page can't be reacehed:
![image](https://github.com/kartoza/Woolpert/assets/139763251/73ed9d37-2fe1-4021-943b-223f7c4b4138)

![image](https://github.com/kartoza/Woolpert/assets/139763251/289287cc-bdab-45bc-b9be-b140e0fff79b)

**Comment by NyakudyaA** [comment]
Hi, We are able to fix all those issues, I will address them in an update later

**Comment by NyakudyaA** [comment]
All these have been fixed except one issue https://github.com/kartoza/Woolpert/issues/62
