### ISSUE TITLE
Data Styling

### ISSUE THREAD

**Issue by BooyeWLP** [kartoza/Woolpert#49]
When a dataset is open in a map, is it possible for the user to edit the style of a layer specifically for that map?

## Styling Button
I noticed that there is a styling button, however when I click on it there is an endless login prompt(possibly because you need admin rights for this?):
![image](https://github.com/kartoza/Woolpert/assets/139763251/97cd7e41-1c90-4cf5-98d6-c01c1bae1148)
![image](https://github.com/kartoza/Woolpert/assets/139763251/d77ceb90-7272-4d57-a1e6-cd7d4cf5e94d)

## Clustering
Is it possible for a user to switch off the clustering if they didn't like the clustering style. We found an option in the layer settings, but it seems like clustering is the only option:
![image](https://github.com/kartoza/Woolpert/assets/139763251/f5246724-a742-4f69-aab3-0feb32d2dda5)

**Comment by NyakudyaA** [comment]
@BooyeWLP This is fixed can you try again

**Comment by BooyeWLP** [comment]
@NyakudyaA thank you, it looks like it is fixed now - however whenever I try changing the style - doesn't change it on the map, and it then makes the layer unreadable:
![image](https://github.com/kartoza/Woolpert/assets/139763251/010b013a-b6c9-43b7-abbd-0db22678496a)

**Comment by NyakudyaA** [comment]
![image](https://github.com/kartoza/Woolpert/assets/2510900/6292b7d8-aae8-484e-9962-913bcd3dee0c)
![image](https://github.com/kartoza/Woolpert/assets/2510900/cb0419b5-3d44-49ed-86a0-cab1d98d0d88)

I can see the layer editing capabiltieis here, Can you try a hard refresh or ingocgnito

**Comment by NyakudyaA** [comment]
@BooyeWLP The default style applied with clustering are a bit complex and it is encouraged to copy from a new default template or just copy an SLD from QGIS and overwrite the default one with the contents of the SLD
![Peek 2023-07-17 15-40](https://github.com/kartoza/Woolpert/assets/2510900/e8048837-2a97-4e93-91f6-ec49d3261289)

**Comment by BooyeWLP** [comment]
Great thanks, I wasn't aware that you have to copy the template, I thought you can just change it. Can change it now. If I wanted to remove the cluster but maintain the original style, how could I do this?

**Comment by NyakudyaA** [comment]
Let me ask the team to make an alternate style but without the clustering. @Jeremy-Prior Can you handle this. You need to duplicate the style and remove the cluster logic, then apply this as an alternate style

**Comment by NyakudyaA** [comment]
This is complete
