### ISSUE TITLE
Woolpert staging down

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/Woolpert#67]
The woolpert staging instance is displaying a default geonode instance. 
https://woolpert-geonode.sta.do.kartoza.com/catalogue/#/

![image](https://github.com/kartoza/Woolpert/assets/107027990/44c297b2-a8f3-48a7-956e-b7a381d90ce3)

**Comment by NyakudyaA** [comment]
@EliVolsch This needs to be discussed from a DevOps perspective. What info should get replicated to staging and at what point should the staging be populated? We can manually do a dump of the dev and restore into staging but we need a procedure for this

**Comment by EliVolsch** [comment]
This issue has been resolved. Staging is now available at https://woolpert-geonode.sta.do.kartoza.com/
