### ISSUE TITLE
Document / Video viewer does not display 

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/Woolpert#68]
Initial testing show the viewer does not display the files. There might be a problem with uploading to the platform. Both .pdf and mp4 files does not display withing the viewer. When downloading these files they can also not be viewed as the produce errors. I uploaded an item to test if it was the data but found the same result when trying to view and download the document

![image_1690871916834_0](https://github.com/kartoza/Woolpert/assets/107027990/7992fddd-71b5-412c-9587-b088c3023717)

![image_1690872070478_0](https://github.com/kartoza/Woolpert/assets/107027990/5e6174f8-a0ea-49e7-87a6-288887b28599)
![image_1690872101537_0](https://github.com/kartoza/Woolpert/assets/107027990/ad81a2ea-cda1-4ed3-87ee-7ce869730d41)

My own test
![image](https://github.com/kartoza/Woolpert/assets/107027990/7a24cae9-6b62-42b9-83ef-4f7758faed24)

**Comment by NyakudyaA** [comment]
We need to set the following
`MAX_DOCUMENT_SIZE=200`

**Comment by NyakudyaA** [comment]
This is fixed
