### ISSUE TITLE
Attribute Pop-ups not showing data

### ISSUE THREAD

**Issue by BooyeWLP** [kartoza/Woolpert#70]
No attributes are showing when we click on the objects on the map
![image](https://github.com/kartoza/Woolpert/assets/139763251/52bc4cc4-fa48-4aae-b8d7-f5deed3349fb)

![image](https://github.com/kartoza/Woolpert/assets/139763251/82a778e3-d41f-406e-8b16-387f8f24c57b)

**Comment by NyakudyaA** [comment]
@BooyeWLP What layer is that ?

**Comment by NyakudyaA** [comment]
![image](https://github.com/kartoza/Woolpert/assets/2510900/7b175488-5100-4b40-a6a4-e82ea0d1668c)
