### ISSUE TITLE
Print function

### ISSUE THREAD

**Issue by BooyeWLP** [kartoza/Woolpert#71]
Is it possible to allow the user to move the print function dialoge up on the screen, when using a smaller screen (like a laptop), I am only allowed to move the window to about 3/4 up in the screen, which causes the bottom part of the window to be cut off.
![image](https://github.com/kartoza/Woolpert/assets/139763251/0d07dc59-c795-4a54-9b4f-e1966199178b)

Would it be possible to change the logo below to a WAPP logo?
![image](https://github.com/kartoza/Woolpert/assets/139763251/7e29c680-b267-490d-9767-b7a2cdd70eca)

**Comment by NyakudyaA** [comment]
The print config has been updated
![image](https://github.com/kartoza/Woolpert/assets/2510900/420e30de-3fe2-4eb1-b171-5a41f17d5d63)

**Comment by NyakudyaA** [comment]
@BooyeWLP I do not understand the first requirement here

**Comment by BooyeWLP** [comment]
Thanks Admire.
re first requirement: When you click on print, a page opens up that allows the user to choose the print settings (title, format etc.). This window extents beyond the bottom of my screen. I can move it up, but it only allows me to move it to a certain height from the top of the map canvas. When I move it up this far, I am still not able to see most of the features in the bottom of the print window. Not sure if that makes any sense?

**Comment by NyakudyaA** [comment]
This is fixed
![image](https://github.com/kartoza/Woolpert/assets/2510900/e06a3f2d-c09c-4de6-9c79-059c88df3ad6)

**Comment by NyakudyaA** [comment]
Closing this and opened a new ticket for enhancement
