### ISSUE TITLE
Layer in Staging Environment Not Available

### ISSUE THREAD

**Issue by BooyeWLP** [kartoza/Woolpert#72]
![image](https://github.com/kartoza/Woolpert/assets/139763251/28aad828-aefa-4876-9dbb-1cf2a8d1c6bc)

**Comment by NyakudyaA** [comment]
Hi @BooyeWLP This might be related to the updates being applied on the layers in the DB by @LunaAsefaw

**Comment by NyakudyaA** [comment]
Layer available 
![image](https://github.com/kartoza/Woolpert/assets/2510900/ced7fd96-95e7-4c89-90cb-f86b39cc21b0)
