### ISSUE TITLE
Can't add recources (maps, datasets, dashboards etc.)

### ISSUE THREAD

**Issue by BooyeWLP** [kartoza/Woolpert#78]
![image](https://github.com/kartoza/Woolpert/assets/139763251/0ec16e97-2257-40d0-b4d3-e4801463a740)

I don't seem to have the option to add resources anymore

**Comment by EliVolsch** [comment]
Please test this functionality again. Permissions to the user profile has been updated

**Comment by NyakudyaA** [comment]
Closing as lack of feedback, assuming this is fixed
