### ISSUE TITLE
Cannot access webpage

### ISSUE THREAD

**Issue by BooyeWLP** [kartoza/Woolpert#85]
![image](https://github.com/kartoza/Woolpert/assets/139763251/62cd019e-d8e9-4c97-87a1-ebe1343bc3c0)

**Comment by NyakudyaA** [comment]
@BooyeWLP You could have tried to access this when it was deploying some updates
![image](https://github.com/kartoza/Woolpert/assets/2510900/74be0bd2-825e-403c-861b-a8f334af5701)

**Comment by NyakudyaA** [comment]
Fixed
